trigger:
- client

steps:

- task: PowerShell@2
  displayName: 'Reemplazando credenciales Telerik'
  inputs:
    targetType: 'inline'
    script: |
      (Get-Content -path "nuget.config" -Raw) -replace '%FeedUsername%', '$(FeedUsername)' | Set-Content -Path "nuget.config"
      (Get-Content -path "nuget.config" -Raw) -replace '%FeedClearTextPassword%', '$(FeedClearTextPassword)' | Set-Content -Path "nuget.config"
      Get-Content -path "nuget.config"
    
- task: PowerShell@2
  displayName: 'Reemplazando credenciales Paltarumi'
  inputs:
    targetType: 'inline'
    script: |
      (Get-Content -path "nuget.config" -Raw) -replace '%PaltarumiFeedUsername%', '$(PaltarumiFeedUsername)' | Set-Content -Path "nuget.config"
      (Get-Content -path "nuget.config" -Raw) -replace '%PaltarumiFeedClearTextPassword%', '$(PaltarumiFeedClearTextPassword)' | Set-Content -Path "nuget.config"
      Get-Content -path "nuget.config"
      
- task: DotNetCoreCLI@2
  displayName: 'Compilando paquete nuget'
  inputs:
    command: 'build'
    arguments: ' --configuration Release'
    projects: '**/Paltarumi.Acopio.Client.csproj'

- task: CopyFiles@2
  displayName: 'Copiando nuget al directorio de artefactos'
  inputs:
    SourceFolder: 'Paltarumi.Acopio.Client/bin/Release'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
- task: DotNetCoreCLI@2
  displayName: 'Publicando paquete nuget'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '6196c24e-d6ba-4e8e-804f-7a16ebc9f727/7d5c5b77-8ad0-46b8-b485-8755436e7213'
