//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paltarumi.Acopio.Balanza.Domain.Resources.Acopio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoteOperacion {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoteOperacion() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paltarumi.Acopio.Balanza.Domain.Resources.Acopio.LoteOperacion", typeof(LoteOperacion).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Lote.
        /// </summary>
        internal static string CodigoLote {
            get {
                return ResourceManager.GetString("CodigoLote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdLoteOperacion.
        /// </summary>
        internal static string IdLoteOperacion {
            get {
                return ResourceManager.GetString("IdLoteOperacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lote no existe.
        /// </summary>
        internal static string LoteNoExiste {
            get {
                return ResourceManager.GetString("LoteNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo.
        /// </summary>
        internal static string Modulo {
            get {
                return ResourceManager.GetString("Modulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Módulo no existe.
        /// </summary>
        internal static string ModuloNoExiste {
            get {
                return ResourceManager.GetString("ModuloNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación.
        /// </summary>
        internal static string Operacion {
            get {
                return ResourceManager.GetString("Operacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operación no existe.
        /// </summary>
        internal static string OperacionNoExiste {
            get {
                return ResourceManager.GetString("OperacionNoExiste", resourceCulture);
            }
        }
    }
}
