USE Acopio
GO

--*********************************************************************************************************************************************
-- MAESTRO
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'01', N'00', N'ESTADO TIPO MINERAL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'01', N'01', N'LLAMPO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'01', N'02', N'CRUDO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'01', N'03', N'POLVEADO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'02', N'00', N'UNIDAD DE MEDIDA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'02', N'01', N'GRANEL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'02', N'02', N'SACOS', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'02', N'03', N'BIG BAG', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'03', N'00', N'ESTADO LOTES', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'03', N'01', N'EN CANCHA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'03', N'02', N'RETIRADO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'03', N'03', N'ANULADO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'04', N'00', N'TIPO LOTE RECODIFICACIÓN', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'04', N'01', N'INICIAL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'04', N'02', N'REMUESTREO DE CANCHA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'04', N'03', N'REMUESTREO DE SACO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'05', N'00', N'VEHICULO MARCA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'06', N'00', N'VEHICULO TIPO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'00', N'CHECKLIST', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'08', N'00', N'ESTADO TMH', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'00', N'TIPO MATERIAL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'05', N'01', N'MITSUBISHI', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'05', N'02', N'VOLVO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'05', N'03', N'SCANIA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'05', N'04', N'VOLKSWAGEN', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'06', N'01', N'CAMIÓN', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'06', N'02', N'VOLQUETE', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'06', N'03', N'PLATAFORMA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'01', N'GUÍA DE RECEPCIÓN DE MINERAL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'02', N'TICKET DE PESAJE', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'03', N'GUÍA DE REMISIÓN REMITENTE', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'04', N'GUÍA DE REMISIÓN TRANSPORTISTA', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'05', N'CONSULTA SUNAT', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'06', N'AUTORIZACIÓN DE COMPROBANTE (GRR)', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'07', N'AUTORIZACIÓN DE COMPROBANTE (GRT)', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'08', N'REINFO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'09', N'CONSULTA MINEROS FORMALIZADOS', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'10', N'RECPO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'11', N'CONSULTA VEHÍCULO SUNARP', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'12', N'COMODATO', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'07', N'13', N'CONSULTA DE LICENCIAS MTC', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'08', N'01', N'A', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'08', N'02', N'B', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'08', N'03', N'C', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'08', N'04', N'D', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'01', N'MOC', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'02', N'MOLL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'03', N'MOP', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'04', N'MSC', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'05', N'MSLL', 1)
INSERT balanza.Maestro ( codigoTabla, codigoItem, descripcion, activo) VALUES ( N'09', N'06', N'MSP', 1)
GO

--*********************************************************************************************************************************************

