//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paltarumi.Acopio.Balanza.Domain.Resources.Balanza {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoteBalanza {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoteBalanza() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paltarumi.Acopio.Balanza.Domain.Resources.Balanza.LoteBalanza", typeof(LoteBalanza).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo de lote no encontrada.
        /// </summary>
        public static string Codigo {
            get {
                return ResourceManager.GetString("Codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoteBalanza-{0:yyyyMMdd-HHmmss}.
        /// </summary>
        public static string ExcelReportName {
            get {
                return ResourceManager.GetString("ExcelReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoteBalanza.
        /// </summary>
        public static string ExcelReportTitle {
            get {
                return ResourceManager.GetString("ExcelReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdLoteBalanza.
        /// </summary>
        public static string IdLoteBalanza {
            get {
                return ResourceManager.GetString("IdLoteBalanza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suma de peso tickets no concide con original.
        /// </summary>
        public static string PesoTicketNoConcideConOriginal {
            get {
                return ResourceManager.GetString("PesoTicketNoConcideConOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de vehículo no fue encontrado.
        /// </summary>
        public static string TipoVehiculoNotFound {
            get {
                return ResourceManager.GetString("TipoVehiculoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La marca de vehículo no fue encontrada.
        /// </summary>
        public static string VehiculoMarcaNotFound {
            get {
                return ResourceManager.GetString("VehiculoMarcaNotFound", resourceCulture);
            }
        }
    }
}
