version: "3"
services:
  paltarumi-balanza-service:
    image: paltarumi-balanza-service
    restart: always
    environment:
      ASPNETCORE_URLS: http://+:80
      DOTNET_USE_POLLING_FILE_WATCHER: 1
      NUGET_PACKAGES: c:\.nuget\fallbackpackages2
      NUGET_FALLBACK_PACKAGES: c:\.nuget\fallbackpackages;c:\.nuget\fallbackpackages2
      ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS: "true"
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_RUNNING_IN_CONTAINER: "true"
      DOTNET_VERSION: 6.0
      ASPNET_VERSION: 6.0
      LOGGING__CONSOLE__FORMATTERNAME: Json
      CN_ACOPIO_BALANZA: "Data Source=192.168.8.24;Initial Catalog=AcopioQA;User ID=sa; Password=@SistemaAcopio1;"
      CN_ACOPIO_SECURITY: "Data Source=192.168.8.24;Initial Catalog=AcopioQASeguridad;User ID=sa; Password=@SistemaAcopio1;"
      URL_SERVICE_AUDIT: "http://192.168.8.24:8090/"
      URL_SERVICE_SECURITY: "http://192.168.8.24:8091/"
    ports:
      - 8080:80
    build:
      context: ./
      dockerfile: Dockerfile
    volumes: 
      - paltarumi-balanza-log:/Logs
    networks:
      - paltarumi-red
networks:
    paltarumi-red:
      name: paltarumi-red
volumes:
    paltarumi-balanza-log:
        name: paltarumi-balanza-log