//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paltarumi.Acopio.Balanza.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paltarumi.Acopio.Balanza.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue creado correctamente.
        /// </summary>
        internal static string CreateSuccessMessage {
            get {
                return ResourceManager.GetString("CreateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {CustomMessage}.
        /// </summary>
        internal static string CustomValidationMessage {
            get {
                return ResourceManager.GetString("CustomValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CustomMessage.
        /// </summary>
        internal static string CustomValidationMessageArgument {
            get {
                return ResourceManager.GetString("CustomValidationMessageArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro a eliminar no fue encontrado.
        /// </summary>
        internal static string DeleteRecordNotFound {
            get {
                return ResourceManager.GetString("DeleteRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue eliminado correctamente.
        /// </summary>
        internal static string DeleteSuccessMessage {
            get {
                return ResourceManager.GetString("DeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código único ya fue registrado.
        /// </summary>
        internal static string DuplicateCodigoUnicoConcesionRecord {
            get {
                return ResourceManager.GetString("DuplicateCodigoUnicoConcesionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue creado anteriormente.
        /// </summary>
        internal static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Ruc ya fue registrado.
        /// </summary>
        internal static string DuplicateRucRecord {
            get {
                return ResourceManager.GetString("DuplicateRucRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dd/MM/yyyy HH:mm:ss.
        /// </summary>
        internal static string ExcelFormatFecha {
            get {
                return ResourceManager.GetString("ExcelFormatFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paltarumi.
        /// </summary>
        internal static string ExcelReportAuthor {
            get {
                return ResourceManager.GetString("ExcelReportAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se econtraron registros.
        /// </summary>
        internal static string ExcelReportEmpty {
            get {
                return ResourceManager.GetString("ExcelReportEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener como máximo {1} caracteres.
        /// </summary>
        internal static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} debe tener como mínimo {1} caracteres.
        /// </summary>
        internal static string FieldMinLength {
            get {
                return ResourceManager.GetString("FieldMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo {0} es requerido.
        /// </summary>
        internal static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro no fue encontrado.
        /// </summary>
        internal static string GetRecordNotFound {
            get {
                return ResourceManager.GetString("GetRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información a procesar es requerida.
        /// </summary>
        internal static string InformationRequired {
            get {
                return ResourceManager.GetString("InformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de página.
        /// </summary>
        internal static string PageField {
            get {
                return ResourceManager.GetString("PageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El número de página debe ser mayor a 0.
        /// </summary>
        internal static string PageFieldMinValue {
            get {
                return ResourceManager.GetString("PageFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de Página.
        /// </summary>
        internal static string PageSizeField {
            get {
                return ResourceManager.GetString("PageSizeField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de página debe ser cómo máximo 1000.
        /// </summary>
        internal static string PageSizeFieldMaxValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tamaño de página debe ser mayor a 0.
        /// </summary>
        internal static string PageSizeFieldMinValue {
            get {
                return ResourceManager.GetString("PageSizeFieldMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error exportando el reporte.
        /// </summary>
        internal static string ReportExportError {
            get {
                return ResourceManager.GetString("ReportExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de reporte no fue encontrado.
        /// </summary>
        internal static string ReportFileDoesNotExist {
            get {
                return ResourceManager.GetString("ReportFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los parámetros de la búsqueda son requeridos.
        /// </summary>
        internal static string SearchInformationRequired {
            get {
                return ResourceManager.GetString("SearchInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los parámetros de paginado de la búsqueda son requeridos.
        /// </summary>
        internal static string SearchPageInformationRequired {
            get {
                return ResourceManager.GetString("SearchPageInformationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las direcciones de ordenamiento solo pueden ser &apos;asc&apos; o &apos;desc&apos;.
        /// </summary>
        internal static string SortDirectionNotValid {
            get {
                return ResourceManager.GetString("SortDirectionNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requiere el IdLote para continuar.
        /// </summary>
        internal static string UpdateLoteCodigo {
            get {
                return ResourceManager.GetString("UpdateLoteCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro a actualizar no fue encontrado.
        /// </summary>
        internal static string UpdateRecordNotFound {
            get {
                return ResourceManager.GetString("UpdateRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro fue actualizado correctamente.
        /// </summary>
        internal static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
    }
}
