// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paltarumi.Acopio.Balanza.Repository.Data;

#nullable disable

namespace Paltarumi.Acopio.Balanza.Apis.Migrations.AuditDb
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20220829013711_AuditMigration_00")]
    partial class AuditMigration_00
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Paltarumi.Acopio.Balanza.Repository.Audit.AuditDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuditHeaderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuditHeaderId");

                    b.ToTable("AuditDetail");
                });

            modelBuilder.Entity("Paltarumi.Acopio.Balanza.Repository.Audit.AuditHeader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AuditHeader");
                });

            modelBuilder.Entity("Paltarumi.Acopio.Balanza.Repository.Audit.AuditDetail", b =>
                {
                    b.HasOne("Paltarumi.Acopio.Balanza.Repository.Audit.AuditHeader", "AuditHeader")
                        .WithMany("AuditDetails")
                        .HasForeignKey("AuditHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditHeader");
                });

            modelBuilder.Entity("Paltarumi.Acopio.Balanza.Repository.Audit.AuditHeader", b =>
                {
                    b.Navigation("AuditDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
